name: sales_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  flutter: 
    sdk: flutter
  camera: ^0.10.3
  app_settings: ^4.2.0
  geolocator: ^9.0.2
  permission_handler: ^10.2.0
  path_provider: ^2.0.12
  flutter_map: ^3.1.0
  latlng: ^0.2.0
  dropdown_button2: ^1.9.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

